services:
  backend-node:
    build:
      context: ./backend-node
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  backend-fastapi:
    build:
      context: ./backend-fastapi
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
  backend-go:
    build:
      context: ./backend-go
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
  backend-cs:
    build:
      context: ./backend-cs
      dockerfile: Dockerfile
    ports:
      - "3003:3003"

  backend-java:
    build:
      context: ./backend-java
      dockerfile: Dockerfile
    ports:
      - "3004:3004"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
        - backend-node
        - backend-fastapi
        - backend-go
        - backend-cs
        - backend-java